apps/contents/courses/urls.py
'''
Created on Sep 30, 2011

@author: javkhlan
'''
from django.conf.urls.defaults import *
from django.contrib.auth import views

# your_app = name of your root django app.
urlpatterns = patterns('openuniversity.apps.contents.courses.views',
    url(r'^$', 'my_courses', name="my_courses"),
    url(r'^add', "course_add"),
#    url(r'^get_courses/$', 'ajax_courses'),
#    url(r'^(?P<c_alias>[\w\-]+)/lessons/$', 'course_lessons'),
#    url(r'^(?P<c_alias>[\w\-]+)/(?P<l_alias>[\w\-]+)/$', 'show_lesson'),
)

apps/contents/stats/urls.py
from django.conf.urls.defaults import *
from openuniversity.apps.contents.stats import views

urlpatterns = patterns('',
    url(r'(?P<user_id>\d+)/(?P<account_lesson_id>\d+)/$', views.view_report, name='report_view'),
)

apps/contents/topics/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth import views

# your_app = name of your root django app.
urlpatterns = patterns('openuniversity.apps.contents.topics.views',
    url(r'^$', 'home'),
    url(r'^get_topics/$', 'ajax_topics'),
    url(r'^(?P<t_alias>[\w\-]+)/lessons/$', 'topic_lessons'),
    url(r'^(?P<t_alias>[\w\-]+)/(?P<l_alias>[\w\-]+)/$', 'show_lesson'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from openuniversity import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.simple import direct_to_template
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^nomadadmin/', include(admin.site.urls)),
    url(r'^', include('openuniversity.apps.home.urls')),
    url(r'^moderator/', include('openuniversity.apps.moderator.urls'), name="moderator"),
    url(r'^profiles/', include('openuniversity.apps.profiles.urls')),
    url(r'^accounts/', include('openuniversity.apps.registration.backends.default.urls')),
    url(r'^topics/practice/', include('openuniversity.apps.contents.practical.topic_practice_urls')),
    url(r'^topics/', include('openuniversity.apps.contents.topics.urls')),
    #url(r'^courses/practice/', include('openuniversity.apps.contents.practical.courses_practice_urls')),
    url(r'^courses/', include('openuniversity.apps.contents.courses.urls')),
    url(r'^common/', include('openuniversity.apps.common.urls')),
    url(r'^get-content/', include('openuniversity.apps.content_installer.server.urls')),
    url(r'^feedback/', include('openuniversity.apps.feedback.urls')),
    url(r'^evaluation/', include('openuniversity.apps.evaluation.urls')),
    url(r'^virtualclassroom/', include('openuniversity.apps.tokbox.urls')),
    url(r'^teacher/', include('openuniversity.apps.teacher_student.teacher.urls')),
    url(r'^report/', include('openuniversity.apps.contents.stats.urls')),
    url(r'^poll/', include('openuniversity.apps.poll.urls')),
#    url(r'^practice/', include('openuniversity.apps.practice.urls')),
#    url(r'^teachers/', include('openuniversity.apps.teachers.urls')),
#    url(r'^challenge/', include('openuniversity.apps.challenge.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^$', direct_to_template,
     #           { 'template': 'base.html' }, name='index'),
)

if settings.DEBUG:
    urlpatterns+= patterns('',
         (r'media/(?P<path>.*)$','django.views.static.serve',{"document_root":settings.MEDIA_ROOT})               
    )

urlpatterns += staticfiles_urlpatterns()

apps/contents/courses/models.py
from django.db import models
from openuniversity.apps.translation.models import TranslateAble
from openuniversity.apps.core.models import Account
from openuniversity.apps.common.models import SubType

# Create your models here.
class Course(TranslateAble):
    contents = models.ManyToManyField(TranslateAble, related_name="courses",
                  through="CourseContents", null=True, blank=True)
    created_account = models.ForeignKey(Account, related_name="courses")
    course_type = models.ForeignKey(SubType)
    started_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    
    def get_trans_field_names(self):
        return ("name", "description")
    def __unicode__(self):
        return self.t9n(field_name="name", current_language=True, 
                        show_language=True)

class CourseContents(models.Model):
    course = models.ForeignKey(Course, related_name="course_contents")
    content = models.ForeignKey(TranslateAble)
    added_account = models.ForeignKey(Account, null=True)
    content_level = models.ForeignKey(SubType, related_name="course_contents")

apps/contents/files/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from openuniversity.apps.core.models import Language, Points
from openuniversity.apps.translation.models import TranslateAble
import commands
import os
import random

def get_pdf_upload_path(instance, filename):
    if hasattr(instance.content, "lesson") and instance.content.lesson != None:
        return os.path.join(
            "content", 
            "%s" % instance.content.lesson.topic.subject.alias_or_id(),
            "%s" % instance.content.lesson.topic.alias(),
            "%s" % instance.content.lesson.alias(),
            "pdf",
            filename)
        
def get_img_upload_path(instance, filename):
    if hasattr(instance, "content"):
        c = instance.content
        if hasattr(c, "lesson") and c.lesson != None:
            return os.path.join(
                "content", 
                "%s" % c.lesson.topic.subject.alias_or_id(),
                "%s" % c.lesson.topic.alias(),
                "%s" % c.lesson.alias(),
                "img",
                filename)
    elif hasattr(instance, "question") and instance.question != None:
        return os.path.join(
           "content", 
            "%s" % instance.question.exercises.all()[0].lesson.topic.subject.alias_or_id(),
            "%s" % instance.question.exercises.all()[0].lesson.topic.alias(),
            "%s" % instance.question.exercises.all()[0].lesson.alias(),
            "exercises",
            "%s" % instance.question.exercises.all()[0].alias(),
            "%s" % instance.question.id,
            "answers",
            filename)

def get_video_upload_path(instance, filename):
    c = instance.content
    if hasattr(c, "lesson") and c.lesson != None:
        return os.path.join(
            "content", 
            "%s" % c.lesson.topic.subject.alias_or_id(),
            "%s" % c.lesson.topic.alias(),
            "%s" % c.lesson.alias(),
            "vdo",
            filename)
    elif hasattr(c, "question") and c.question != None:
        print "question"
        return os.path.join(
            "content", 
            "%s" % c.question.exercises.all()[0].lesson.topic.subject.alias_or_id(),
            "%s" % c.question.exercises.all()[0].lesson.topic.alias(),
            "%s" % c.question.exercises.all()[0].lesson.alias(),
            "exercises",
            "%s" % c.question.exercises.all()[0].alias(),
            "%s" % c.question.id,
            "vdo",
            filename)
def get_subtitle_upload_path(instance, filename):
    c = instance.content
    if hasattr(c, "lesson") and c.lesson != None:
        return os.path.join(
            "content", 
            "%s" % c.lesson.topic.subject.alias_or_id(),
            "%s" % c.lesson.topic.alias(),
            "%s" % c.lesson.alias(),
            "vdo",
            filename)
    elif hasattr(c, "question") and c.question != None:
        print "question"
        return os.path.join(
            "content", 
            "%s" % c.question.exercises.all()[0].lesson.topic.subject.alias_or_id(),
            "%s" % c.question.exercises.all()[0].lesson.topic.alias(),
            "%s" % c.question.exercises.all()[0].lesson.alias(),
            "exercises",
            "%s" % c.question.exercises.all()[0].alias(),
            "%s" % c.question.id,
            "vdo",
            filename)

def get_upload_path(instance, filename):
    return ""

# Create your models here.
class Video(models.Model):
    url_path = models.URLField(null=True, blank=True)
    url_path_embed = models.URLField(null=True, blank=True)
    file = models.FileField(upload_to=get_video_upload_path, null=True, 
            blank=True, verbose_name=_("file with a 'flv' format"))
    subtitle = models.FileField(upload_to=get_subtitle_upload_path, 
            null=True, blank=True, verbose_name=_("subtitle file"))
    is_localized = models.BooleanField()
    language = models.ForeignKey(Language)
    created_date = models.DateTimeField(auto_now=True)
    content = models.ForeignKey(TranslateAble, null=True, blank=True)
    points = models.ForeignKey(Points, null=True, blank=True)
    has_thumbnails = models.BooleanField(default=False)
    thumbnail_path = models.FilePathField(null=True, blank=True)
        
    def __unicode__(self):
        return (self.is_localized and self.file) or self.url_path
    
    def subtitle_file(self):
        return (self.is_localized and self.subtitle) or ""
    
    def create_video_thumbnails(self):
        print "------------"
        file_separator = "/"
        name = self.file.path.split(file_separator)[-1]
        pwd = file_separator.join(self.file.path.split(file_separator)[:-1])
        duration = int(commands.getoutput("""ffmpeg -i %s 2>&1 | grep totalduration | awk '{ print $3 }'""" % self.file.path))
        frame_rate = int(commands.getoutput("""ffmpeg -i %s 2>&1 | grep framerate | awk '{ print $3 }'""" % self.file.path))
        total_frames = int(duration) * int(frame_rate)
        for i in range(1, 6):
            multiplier = random.random() * total_frames / total_frames
            print float(duration*multiplier)
            print duration, multiplier
            print "ffmpeg  -ss %f -i %s -f image2 -vframes 1 %s.jpg" % (
                duration*multiplier, self.file.path, pwd+file_separator+name.split(".")[0]+"-"+str(i))
            commands.getoutput("ffmpeg  -ss %f -i %s -f image2 -vframes 1 %s.jpg" % (
                duration*multiplier, self.file.path, pwd+file_separator+name.split(".")[0]+"-"+str(i)))
    def get_thumbnails(self):
        if self.has_thumbnails:
            file_separator = "/"
            name = self.file.path.split(file_separator)[-1]
            return [ file_separator.join(self.file.__unicode__().split(file_separator)[:-1]) + file_separator + name.split(".")[0]+"-"+str(t)+".jpg" for t in range(1,6) ]

class PDFFile(models.Model):
    file = models.FileField(upload_to=get_pdf_upload_path, verbose_name=_("file"))
    is_localized = models.BooleanField(default=False)
    url_path = models.URLField(null=True, blank=True)
    content = models.ForeignKey(TranslateAble, null=True, blank=True)
    name = models.CharField(max_length=30, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.name:
            file_separator = "/"
            self.name = self.file.path.split(file_separator)[-1]
        super(PDFFile, self).save(*args, **kwargs)
    
class Image(models.Model):  
    image_file = models.ImageField(upload_to=
                                get_img_upload_path, null=True,blank=True)
    content = models.ForeignKey(TranslateAble)
    is_localized = models.BooleanField()

    def __unicode__(self):
        return self.image_file
    
    def thumbnail(self):
        return self.image_file.file.__unicode__() + u"_thumb"

apps/contents/courses/forms.py
'''
Created on Oct 6, 2011

@author: javkhlan
'''
from django import forms
from openuniversity.apps.contents.courses.models import Course
from openuniversity.apps.translation.forms import \
    AutoCurrentLanguageTranslateAbleForm
from openuniversity.apps.common.models import SubType

class CourseForm(AutoCurrentLanguageTranslateAbleForm):
    
    name = forms.CharField(max_length=50)
    description = forms.CharField(max_length=12500, widget=forms.Textarea)
    course_type = forms.ModelChoiceField(
             queryset=SubType.objects.filter(table_name=Course._meta.db_table),
             widget=forms.RadioSelect)
    
    class Meta:
        model = Course
        exclude = ("contents", "created_account")
        

apps/contents/stats/forms.py
#coding: utf-8
'''
Created on Sep 26, 2011

@author: javkhlan
'''
from django import forms
from openuniversity.apps.contents.stats.models import Account_Lesson_Question, \
    Account_Lesson, CompletedExercise

class Account_Topic_QuestionForm(forms.ModelForm):
    class Meta:
        model = Account_Lesson_Question

class Account_LessonForm(forms.ModelForm):
    class Meta:
        model = Account_Lesson

class CompletedLessonExerciseForm(forms.ModelForm):
    class Meta:
        model = CompletedExercise

apps/contents/files/views.py
# Create your views here.

apps/contents/stats/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from openuniversity.apps.contents.stats.utils import Report
from openuniversity.apps.contents.stats.models import Account_Lesson
from openuniversity.apps.moderator.views import is_moderator as mod_check

@login_required
def view_report(request, user_id, account_lesson_id):
    try:
        profile_obj = request.user.get_profile()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('profiles_create_profile'))
    
    user_id = long(user_id)
    is_moderator = mod_check(profile_obj.user)
    if is_moderator:
        teacher = True
        reported_fullname = get_object_or_404(User, id=user_id).get_full_name()
    elif user_id == profile_obj.user.id:
        teacher = False
        reported_fullname = profile_obj.user.get_full_name()
    else:
        #Cant let a student view someone else's report :)
        return HttpResponseRedirect(reverse('openuniversity.apps.home.views.index'))
    
    account_lesson = Account_Lesson.objects.get(id=account_lesson_id)
    report = Report(account_lesson, teacher)
    
    return render_to_response( "contents/stats/view-report.html", 
                               locals(), context_instance=RequestContext(request))

apps/contents/topics/views.py
#coding: utf-8
from django.db.models.query_utils import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from openuniversity.apps.contents.contents_core.models import Subject, Topic, \
    ContentAlias
from openuniversity.apps.contents.practical.models import Lesson
from openuniversity.apps.contents.stats.models import Account_Lesson, \
    CompletedExercise
from openuniversity.apps.core.models import AgeGroup
from openuniversity.apps.common.models import SubType

def home(request):
    subjects = Subject.objects.all()
    age_groups = AgeGroup.objects.all()
    return render_to_response("contents/topic/home.html", locals(),
                              context_instance=RequestContext(request))

def ajax_topics(request):
    subjects = [int(s) for s in request.GET['s'].strip().split(",")[1:]]
    age_groups = [int(ag) for ag in request.GET['ag'].strip().split(",")[1:]]
    topics = Topic.objects.all()
    if age_groups:
        topics = topics.filter(age_group__id__in=age_groups)
    if subjects:
        topics = topics.filter(subject__id__in=subjects)
    print topics
    return render_to_response("contents/topic/ajax_topics.html", locals(), 
                              context_instance=RequestContext(request))
    
def topic_lessons(request, t_alias):

    try:
        topic = Topic.objects.get(pk=int(t_alias))
    except:
        topic = ContentAlias.objects.get(alias=t_alias).content_object    
    lessons = topic.lessons.all()
    if request.user.is_superuser:
        return HttpResponseRedirect("/courses/")
    
    return render_to_response("contents/topic/lesson/list.html", locals(),
                              context_instance=RequestContext(request))

def show_lesson(request, t_alias, l_alias):

    try:
        lesson = ContentAlias.objects.get(alias=l_alias).content_object    
    except:
        lesson = Lesson.objects.get(pk=int(l_alias))
    exercises = lesson.exercises.all()

    a_l = None
    try:
        l_id = int(l_alias)
    except:
        l_id = ContentAlias.objects.get(alias=l_alias).content_object.id

    # no admins allowed!
    if request.user.is_superuser:
        return HttpResponseRedirect("/courses/")
    
    if not request.user.is_anonymous():
        if Account_Lesson.objects.filter(
               Q(account=request.user.get_profile())&
               Q(lesson__id=l_id)
               ).count() == 1:
            a_l = Account_Lesson.objects.get(
                      Q(account=request.user.get_profile())&
                      Q(lesson__id=l_id)
                  )
    if not a_l:
        for e in exercises:
            e.is_finished = False
    else:
        for e in exercises:
            if (e.id,) in CompletedExercise.objects.filter(account_lesson=a_l).values_list("exercise__id"):
                e.is_finished = True
            else:
                e.is_finished = False
                
    q_types = SubType.objects.all()
                
    return render_to_response("contents/topic/lesson/view.html", locals(),
                              context_instance=RequestContext(request))

templates/contents/practice/ask-start-practice.html
{% extends "base.html" %}
{% load i18n %}
{% load translate %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block grey_wrapper %}
{% trans "Start Practice" %}
{% endblock%}

{% block title %}
Open University - {% trans "Start Practice" %}
{% endblock %}

{% block content %}
<div id="middle_container">
<div class="ask">
    {% if no_questions %}
        {% trans "we are sorry but there are no questions added in this exercise" %}
    {% else %}
        {% if sign_in_reminder %}
            {% trans "Taking these exercises without signing in your progress won't be saved, so please sign in or register if you have not done so!" %}
	{% endif %}
<br>
        {% trans "You are going to start exercise" %} "{% t9n practice_exercise "name" %}" {% trans "from lesson" %} 
<br>
        "{% t9n practice_exercise.lesson "name" %}" {% trans "of topic" %} {% t9n practice_exercise.lesson.topic "name" %}
     <div class="both-button">
     	<div class="button-back"><a href="../../{{practice_exercise.lesson.topic.alias}}/{{practice_exercise.lesson.alias}}">{% trans "view lesson" %}</a></div>
        {% if not no_resume%}
        <div class="button-middle"><a href="{{form_action}}">{% trans "Resume practice" %}</a></div>
        <div class="button-next"><a href="1/reset">{% trans "Restart practice" %}</a></div>
        {% else %}
        <div class="button-next"><a href="1/reset">{% trans "Start practice" %}</a></div>
        {% endif %}
        
    </div>
    {% endif %}
</div>
</div><!-- #left_container -->
{% endblock %}

templates/contents/practice/practice-result.html
{% extends "base.html" %}
{% load i18n %}
{% load translate %}

{% block title %}
	Open University
{% endblock %}

{% block grey_wrapper %}
	{% trans "Your result:" %}
{% endblock %}

{% block content %}
{% trans "you've answered all the questions in the current topic's exercise" %}<br>
{% trans "exercise" %}: {% t9n topic "name" %} > {% t9n exercise.lesson "name" %} > {% t9n exercise "name" %} <br>
{% trans "questions (answered/total)" %}: ({{ questions_answered }}/{{ questions_total }})
<br>
{% trans "go" %} <a href="../../../{{exercise.lesson.topic.alias}}/{{exercise.lesson.alias}}/">{% trans "back" %}</a> {% trans "to topic page" %}
	
{% endblock %}

templates/contents/practice/practice.html
{% extends "base.html" %}
{% load i18n %}
{% load translate %}

{% block title %}
Open University - {% trans "Practice" %}
{% endblock %}

{% block grey_wrapper %}
{% trans "Practice" %}
{% endblock%}

{% block js %}
<script type='text/javascript' src='/media/jwplayer/jwplayer.js'></script>
<script type='text/javascript' src='/media/jwplayer/swfobject.js'></script>
<script type="text/javascript" src="/media/lightbox/js/jquery.lightbox-0.5.js"></script>
<script type="text/javascript">
$(function() {
    $('#gallery a').lightBox();
});
</script>
<script type="text/javascript">
$(document).ready(function() 
{
{% if question.has_video %}
    jwplayer('video').setup({
  	'flashplayer': '/media/jwplayer/player.swf',
    'id': 'playerID',
    'width': '480',
    'height': '300',
	{% if question.video.is_localized %}
    'file': '/media/{{question.video.file}}',
	{% else %}
	'file': '{{question.video.url_path}}',
	{% endif %}
	{% if question.video.subtitle_file %}
    'plugins': {
      "captions-2": {
        back: false,
        file: "/media/{{question.video.subtitle_file}}",
      }
    },
    {% endif %}
  });
{% endif %}
  safe_images();
});
function vote_for_question()
{
	data = {}
	$.ajax({
		type: "GET",
		url: "/students/vote/{{question.id}}/",
		data: data,
		success: function(resp)
		{
			alert(resp);
			$("#votes").html(parseInt($("#votes")).html()+1);
		}
	});			
}

function safe_images()
{
	str = document.getElementById("practice_form").innerHTML;
	var patt=new RegExp("&lt;img","gi");
	str2 = str.replace(patt, "<img");
	document.getElementById("practice_form").innerHTML = str2;
}
</script>

<!-- Begin Using Cufon -->
<script type="text/javascript">
			Cufon.replace('.qtitle');
</script>
<!-- End Using Cufon -->
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/media/lightbox/css/jquery.lightbox-0.5.css" media="screen" />
<style type="text/css">
    /* jQuery lightBox plugin - Gallery style */
    #gallery {
        padding: 10px;
    }
    #gallery ul { list-style: none; }
    #gallery ul li {float:left; margin-right:8px; margin-bottom:8px; }
    #gallery ul img {
        border: 5px solid #fff;
    }
    
    #gallery ul a:hover img {
        border: 5px solid #fff;
        color: #fff;
    }
    #gallery ul a:hover { color: #fff; }
</style>
{% endblock %}

{% block content %}

{%if is_incorrect%}
	{% trans "You have answered incorrectly" %}
{%endif%}
<div id="left_container">
	{% if request.user.message_set.all %}  
	<ul>
		<li>{{ logged_account.get_last_user_msg }}</li>	</ul>
	{% endif %}

    	<div class="grey-box"><div class="qtitle">{% trans "Question" %}</div><div class="qtext">{{ question }}</div></div>
    
	{% if question.has_video %}
    <div id="video_container">
        <div id="video">
            <p>{% trans "no video available for this topic" %}</p>
        </div>
        <div id="functions">
        	<img src="{{question.image}}"><img>
        </div>
    </div>
    
	{% endif %}
	<form method="POST" action="../{{form.action}}/">
		<input type="hidden" name="question_id" value="{{question.id}}">
	{% csrf_token %}
<ul id="practice_form">
	{% for field in form %}
        {% if field.is_hidden %}
		{{ field }}
		{% else %}
        <li><div class="grey-box"><div class="qtitle">{{ field.label_tag }}&nbsp;</div><div class="qtext">{{ q.answer_type }}</div></div> {{ field }}</li>
		{% endif %}
	{% endfor %}
</ul>
	</table>
<div id="practice-buttons">	
	<input type="submit" class="practice_submit" name="submit" value="answer">
	<input type="submit" class="practice_next" name="submit" value="skip">

	<div class="total-hint">
		{% if hint %}
        <a  href="" onclick="alert('{% t9n question "hint" %}'); return false">hint</a>
        {% endif %}
        <!--
        {% if request.user.is_authenticated %}
            {% trans "total votes" %} : <span id="votes">{% if question.votes %}{{question.votes}}{%else%}0{%endif%}</span>
        {% endif %}
        <a href="" onclick="vote_for_question(); return false">vote</a>
        <a href="" onclick="alert('functionality not implemented'); return false">share</a>
        -->
	</div>
</div></form>
</div>

<div id="right_container">
<div id="badge_container">
<div class="badge-title">{% trans "Badges" %}</div>
{% trans "Max Points" %}: {{practice_exercise.lesson.get_possible_total_points}}
</div>
        
<div id="textbook_container" class="margin_top_bot">
<div class="textbook-title"> {% trans "Image Album:" %}</div>
<div id="gallery">
<ul>
{% for image_item in practice_exercise.lesson.image_set.all %}
<li>
<a href="{{image_item.image_file.file}}" title="">
<img src="{{image_item.thumbnail}}" width="72" height="72" alt="" />
</a>
</li>
{% endfor %}
</ul>
</div><!-- .gallery -->
</div><!-- textbook_container-->
</div><!-- right-container -->
{% endblock %}