apps/profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *
from openuniversity.apps.profiles import views


urlpatterns = patterns('',
    url(r'^lang/$', views.set_lang, name='set_lang'),
    url(r'^lang/$', views.set_lang, name='set_lang'),
    url(r'^create/$', views.create_profile, name='profiles_create_profile'),
    url(r'^ajax', views.get_ajax_response, name='profiles_get_ajax'),
    url(r'^edit/$', views.edit_profile, name='profiles_edit_profile'),
    url(r'^(?P<username>\w+)/$', views.profile_detail, name='profiles_profile_detail'),
    url(r'^$', views.profile_list, name='profiles_profile_list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from openuniversity import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.simple import direct_to_template
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^nomadadmin/', include(admin.site.urls)),
    url(r'^', include('openuniversity.apps.home.urls')),
    url(r'^moderator/', include('openuniversity.apps.moderator.urls'), name="moderator"),
    url(r'^profiles/', include('openuniversity.apps.profiles.urls')),
    url(r'^accounts/', include('openuniversity.apps.registration.backends.default.urls')),
    url(r'^topics/practice/', include('openuniversity.apps.contents.practical.topic_practice_urls')),
    url(r'^topics/', include('openuniversity.apps.contents.topics.urls')),
    #url(r'^courses/practice/', include('openuniversity.apps.contents.practical.courses_practice_urls')),
    url(r'^courses/', include('openuniversity.apps.contents.courses.urls')),
    url(r'^common/', include('openuniversity.apps.common.urls')),
    url(r'^get-content/', include('openuniversity.apps.content_installer.server.urls')),
    url(r'^feedback/', include('openuniversity.apps.feedback.urls')),
    url(r'^evaluation/', include('openuniversity.apps.evaluation.urls')),
    url(r'^virtualclassroom/', include('openuniversity.apps.tokbox.urls')),
    url(r'^teacher/', include('openuniversity.apps.teacher_student.teacher.urls')),
    url(r'^report/', include('openuniversity.apps.contents.stats.urls')),
    url(r'^poll/', include('openuniversity.apps.poll.urls')),
#    url(r'^practice/', include('openuniversity.apps.practice.urls')),
#    url(r'^teachers/', include('openuniversity.apps.teachers.urls')),
#    url(r'^challenge/', include('openuniversity.apps.challenge.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^$', direct_to_template,
     #           { 'template': 'base.html' }, name='index'),
)

if settings.DEBUG:
    urlpatterns+= patterns('',
         (r'media/(?P<path>.*)$','django.views.static.serve',{"document_root":settings.MEDIA_ROOT})               
    )

urlpatterns += staticfiles_urlpatterns()

apps/profiles/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from openuniversity.apps.core.models import AgeGroup, Division
from django.contrib.auth.models import User
from openuniversity.apps.core.models import Account
from openuniversity.apps.teacher_student.student.models import Student_Division

# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}
GENDER_CHOICES = (
    (True,_('Male')),
    (False,_('Female')),
)

ALL_AGE_GROUPS = AgeGroup.objects.all()
ALL_DIVISIONS = Division.objects.all()

class DivisionModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("E-mail"))
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())
    birthdate = forms.DateField(widget=forms.DateInput(attrs=attrs_dict),label=_("Birth date"))
    location = forms.CharField(max_length=100)
    
    def save(self,profile_obj):
        data = self.cleaned_data
        user = User.objects.get(id=profile_obj.user.id)
        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.email = data['email']
        user.save()
        account = Account.objects.get(user=user)
        account.gender = data['gender']
        account.birthdate = data['birthdate']
        account.location = data['location']
        account.save()
        
        
class StudentProfileForm(ProfileForm):
        age = forms.ModelChoiceField(queryset=ALL_AGE_GROUPS, empty_label=_("Choose your grade"), required=False)
        division = DivisionModelChoiceField(queryset=ALL_DIVISIONS, empty_label=_("Choose grade first"), required=False)
        
        def save(self,profile_obj):
            data = self.cleaned_data
            super(StudentProfileForm,self).save(profile_obj)
            try:
                student = profile_obj.student_division
                student.division = data['division']
            except Student_Division.DoesNotExist:
                student = Student_Division.objects.create(student=profile_obj, division = data['division'])
            student.save()

apps/profiles/views.py
"""
Views for creating, editing and viewing site-specific user profiles.

"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list_detail import object_list
from django.utils.translation import activate

from openuniversity.apps.profiles import utils
from openuniversity.apps.profiles.utils import make_custom_datefield
from openuniversity.apps.profiles.forms import StudentProfileForm, ProfileForm
from openuniversity.apps.core.models import AgeGroup, Division
from openuniversity.apps.contents.contents_core.models import Subject,Topic
from openuniversity.apps.contents.stats.models import Account_Lesson, Account_Lesson_Question, CompletedExercise
from openuniversity.apps.teacher_student.student.models import Student_Division
from openuniversity.apps.teacher_student.teacher.models import Topic_Teacher

from openuniversity.apps.moderator.views import is_moderator as mod_check
import json

'''
    View that changes language, eng, mon
    and redirects to last page
    
    GET:
        next
        lang

'''

def set_lang(request):
    
    context = RequestContext(request)
    last_path = request.GET.get("next")
    lang = request.GET.get("lang")
    activate(lang)
    request.session['django_language'] = lang
    return redirect(last_path,context)

    
def create_profile(request, form_class=None, success_url=None,
                   template_name='profiles/create_profile.html',
                   extra_context=None):
    """
    Create a profile for the current user, if one doesn't already
    exist.
    
    If the user already has a profile, as determined by
    ``request.user.get_profile()``, a redirect will be issued to the
    :view:`profiles.views.edit_profile` view. If no profile model has
    been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and creating the user
        profile. This form class must define a method named
        ``save()``, implementing the same argument signature as the
        ``save()`` method of a standard Django ``ModelForm`` (this
        view will call ``save(commit=False)`` to obtain the profile
        object, and fill in the user before the final save). If the
        profile object includes many-to-many relations, the convention
        established by ``ModelForm`` of using a method named
        ``save_m2m()`` will be used, and so your form class should
        also define this method.
        
        If this argument is not supplied, this view will use a
        ``ModelForm`` automatically generated from the model specified
        by ``AUTH_PROFILE_MODULE``.
    
    ``success_url``
        The URL to redirect to after successful profile creation. If
        this argument is not supplied, this will default to the URL of
        :view:`profiles.views.profile_detail` for the newly-created
        profile object.
    
    ``template_name``
        The template to use when displaying the profile-creation
        form. If not supplied, this will default to
        :template:`profiles/create_profile.html`.
    
    **Context:**
    
    ``form``
        The profile-creation form.
    
    **Template:**
    
    ``template_name`` keyword argument, or
    :template:`profiles/create_profile.html`.
    
    """
    try:
        profile_obj = request.user.get_profile()
        return HttpResponseRedirect(reverse('profiles_edit_profile'))
    except ObjectDoesNotExist:
        pass
    
    #
    # We set up success_url here, rather than as the default value for
    # the argument. Trying to do it as the argument's default would
    # mean evaluating the call to reverse() at the time this module is
    # first imported, which introduces a circular dependency: to
    # perform the reverse lookup we need access to profiles/urls.py,
    # but profiles/urls.py in turn imports this module.
    #
    
    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()
        #make_custom_datefield(form_class)
    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            profile_obj = form.save(commit=False)
            profile_obj.user = request.user
            profile_obj.save()
            if hasattr(form, 'save_m2m'):
                form.save_m2m()
            return HttpResponseRedirect(success_url)
    else:
        form = form_class()
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value
    
    return render_to_response(template_name,
                              { 'form': form },
                              context_instance=context)
create_profile = login_required(create_profile)

def edit_profile(request, form_class=None, success_url=None,
                 template_name='profiles/edit_profile.html',
                 extra_context=None):
    """
    Edit the current user's profile.
    
    If the user does not already have a profile (as determined by
    ``User.get_profile()``), a redirect will be issued to the
    :view:`profiles.views.create_profile` view; if no profile model
    has been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.
    
    **Optional arguments:**
    
    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and editing the user
        profile. This form class must operate similarly to a standard
        Django ``ModelForm`` in that it must accept an instance of the
        object to be edited as the keyword argument ``instance`` to
        its constructor, and it must implement a method named
        ``save()`` which will save the updates to the object. If this
        argument is not specified, this view will use a ``ModelForm``
        generated from the model specified in the
        ``AUTH_PROFILE_MODULE`` setting.
    
    ``success_url``
        The URL to redirect to following a successful edit. If not
        specified, this will default to the URL of
        :view:`profiles.views.profile_detail` for the profile object
        being edited.
    
    ``template_name``
        The template to use when displaying the profile-editing
        form. If not specified, this will default to
        :template:`profiles/edit_profile.html`.
    
    **Context:**
    
    ``form``
        The form for editing the profile.
        
    ``profile``
         The user's current profile.
    
    **Template:**
    
    ``template_name`` keyword argument or
    :template:`profiles/edit_profile.html`.
    
    """
    
    try:
        #profile_obj = Account.objects.get(id = request.user.id )
        profile_obj = request.user.get_profile()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('profiles_create_profile'))
    
    #
    # See the comment in create_profile() for discussion of why
    # success_url is set up here, rather than as a default value for
    # the argument.
    #
    is_moderator = mod_check(profile_obj.user)
    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    
    if form_class is None:
        if is_moderator:
            form_class = ProfileForm
        else:
            form_class = StudentProfileForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            form.save(profile_obj=profile_obj)
            return HttpResponseRedirect(success_url)
    else:
        
        data = {'first_name':profile_obj.user.first_name,
                'last_name':profile_obj.user.last_name,
                'email':profile_obj.user.email,
                'gender':profile_obj.gender,
                'birthdate':profile_obj.birthdate,
                'location':profile_obj.location
                }
        if(not is_moderator):
            try:
                current_division = profile_obj.student_division
                data['age'] = current_division.division.age.age
                data['division'] = current_division.division.id
            except Student_Division.DoesNotExist:
                pass
        form = form_class(data)
    
    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value
    #'all_age_groups': all_age_groups,
    
    context_params = {'form':form, 
        'profile':profile_obj}
    if is_moderator:
        context_params['is_moderator'] = is_moderator
        context_params['all_age_groups'] = AgeGroup.objects.all()
        context_params['topic_teacher'] = Topic_Teacher.objects.filter(teacher=profile_obj)

templates/profiles/create_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block js %}
<script type="text/javascript">
$(function() {
		$( "#id_birthdate" ).datepicker();
		$( "#id_birthdate" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
		$( "#id_birthdate" ).datepicker( "setDate" , "1990-1-1" )
	});
</script>
{% endblock %}

{% block content %}
<form method="post" action=".">{% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>
{% endblock %}

templates/profiles/edit_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
NomadEDU - {% trans "profile" %}
{% endblock %}

{% block grey_wrapper %}
{% trans "Profile" %}
{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
		var get_divisions = function(age) {
			var url = "{% url profiles_get_ajax %}" + "?age_group=" + age +"&division=true"
			$.get(url, function(data){
				console.log(data);
				$("#id_division").linkselect("replaceOptions", data["division"]);
				$('#id_division').linkselect("disable",false);
			});
		};
		$( "#id_birthdate" ).datepicker({ changeYear: true, yearRange:"c-80:c", dateFormat: 'yy-mm-dd' });
		//find all form with class jqtransform and apply the plugin
    	$("form.jqtransform").jqTransform();
    	$('#id_age').linkselect({style: "selectbox",
    							 change: function (li, value, text){
    							 	console.log(value);
    							 	get_divisions(value);
    							 }});
    	$('#id_division').linkselect({style: "selectbox"});
    	$('#id_division').linkselect("disable",true);
    	$('#cancel-button').bind('click', function() {
    		window.history.go(-1);
		});
		
		{% if is_moderator %}
		var get_divisions_topics = function(age) {
			var url = "{% url profiles_get_ajax %}" + "?age_group=" + age +"&division=true&topic=true"
			$.get(url, function(data){
				console.log(data);
				$("#division-select").linkselect("replaceOptions", data["division"]);
				$('#division-select').linkselect("disable",false);
				$('#topic-select').linkselect("replaceOptions", data["topic"]);
				$('#topic-select').linkselect("disable",false);
				$('#add-topic-taught-button').button( "option", "disabled", false );
			});
		};
		var remove_topic = function(event) {
			event.preventDefault();
			var target = $(event.target)
			var tt_id = target.attr("data-tt-id");
			var url = "{% url teacher_remove_course %}";
			$.post(url, {id:tt_id}, function(data){
				if(data.success){
					target.parents("tr").remove();
				}
			});
		};
		$('.linkselect').linkselect({style: "selectbox"});
		$('.button-link').button();
		$('#age-group-select').linkselect({style: "selectbox",
							 change: function (li, value, text){
							 	console.log(value);
							 	get_divisions_topics(value);
							 }});
    	$('#division-select').linkselect("disable",true);
		$('#topic-select').linkselect("disable",true);
		$('#add-topic-taught-button').button( "option", "disabled", true );
		$('#add-topic-taught-button').bind('click', function() {
			var url = "{% url teacher_add_course %}";
			$.post(url, $('#topic-taught-form').serialize(), function(data){
				console.log(data);
				var new_row = '<tr><td>'+data.topic+'</td><td>'+data.division+'</td><td><a href="#" data-tt-id="'+data.id+'" class="remove-topic-taught-button">Remove</a></td></tr>';
				$('#topics_taught_list > tbody:last').append(new_row).find('.remove-topic-taught-button').bind('click', remove_topic);
			});
		});
		$('.remove-topic-taught-button').bind('click', remove_topic);
		{% endif %}
	});
</script>
<script type='text/javascript' src='/media/js/jquery.jqtransform.js'></script>
<script type='text/javascript' src='/media/js/jquery.linkselect.min.js'></script>
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/jqtransform.css"/>
<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/jquery.linkselect.style.select.css"/>
<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/edit_profile.css"/>

<div>
	<div id="basic-info">
		<form id="profile-form" class="jqtransform" method="post" action=".">{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td id="profile-edit-button-row" colspan="2">
						<input type="submit" value="{% trans 'Submit' %}" />
						<input id="cancel-button" type="button" value="{% trans 'Cancel' %}" />
					</td>
				</tr>
			</table>
		</form>
	</div>
	{% if is_moderator %}
	<div id="teacher_topic">
		<h2>Topics Taught</h2>
		<table id="topics_taught_list">
			<thead>
				<tr><th>Name</th><th>Division</th><th>&nbsp;</th></tr>
			</thead>
			<tbody>
				{% for tt in topic_teacher%}
				<tr><td>{{tt.topic}}</td><td>{{tt.division}}</td><td><a href="#" data-tt-id="{{tt.id}}" class="remove-topic-taught-button">Remove</a></td></tr>
				{% endfor %}
			</tbody>
		</table>
		<div id="add-topic-taught" class="dropdowns">
			<h4> Add a new topic that you teach </h4>
			<form id="topic-taught-form" method="post">
				{% csrf_token %}
				<span class="multi-select">
					<select id="age-group-select" name="age_group">
						<option value = "0">All Grades</option>
						{% for a in all_age_groups %}
						<option value = "{{ a.age }}">{{a}}</option>	
						{% endfor %}	
					</select>
				</span>
				<span class="multi-select">
					<select id="division-select" name="division" class="linkselect">
						<option value = "0">First select grade</option>
					</select>
				</span>
				<span class="multi-select">
					<select id="topic-select" name="topic" class="linkselect">
						<option value = "0">First select grade</option>
					</select>
				</span>
				<a id="add-topic-taught-button" class="button-link">Add</a>
			</form>
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}

templates/profiles/lesson_list.html
{% load translate %}
{% load i18n %}

<table id="lesson-table" class="display"> 
	<thead> 
		<tr> 
		    <th>Lesson</th> 
		    <th>Grade</th> 
		    <th>Started Date</th> 
		    <th>Finished Date</th> 
		    <th>Points earned</th>
		    <th>View Report</th> 
		</tr> 
	</thead> 
	<tbody> 
		{% for l in lessons %}	
		<tr class="{{ l.lesson.is_completed|yesno:"complete,incomplete" }}">
		    <td><a href="/topics/{{l.lesson.topic.alias}}/{{l.lesson.alias}}/">{% t9n l.lesson "name" %}</a></td> 
		    <td>{{l.lesson.topic.age_group.age}}</td> 
		    <td>{{l.lesson.started_date}}</td> 
		    <td>{{l.lesson.finished_date}}</td> 
		    <td>{{l.lesson.points}}</td> 
		    <td class="last-column"><a href='{% url report_view user_id=user_id account_lesson_id=l.pk %}' target="_blank">View</a></td>
		</tr> 
		{% endfor %} 
	</tbody> 
</table> 

templates/profiles/profile_detail.html
{% extends "base.html" %}

{% load translate %}
{% load i18n %}

{% block js %}
	<script type='text/javascript'>
		$(document).ready(function (){
			console.log("yay");
			$('.linkselect').linkselect({style: "selectbox"});
			
			function initialize_datatable(){
				$("#lesson-table").dataTable({
					"bJQueryUI": true,
			        "bPaginate": false,
			        "bLengthChange": false,
			        "bFilter": true,
			        "bSort": true,
			        "bInfo": true,
			        "bAutoWidth": true,
			        "asStripClasses": null,
			        "aoColumnDefs": [{ "bSortable": false, "aTargets": [ 5 ] }],
			        //"sScrollY": "400px"
			    });
			};
			initialize_datatable();
			$('.button-link').button();
			var fetch_lessons = 
			$('#filter-button').bind('click', function() {
				var url = "?"+$('#lesson-filter-form').serialize();
				console.log(url);
				$.get(url, function(data){
					$('#lessons-div').empty().html(data);
					initialize_datatable();
				});
			});
			{% if is_moderator%}
			$('#student-select').linkselect({style: "selectbox",
							 change: function (li, value, text){
							 	console.log(value);
							 	$('#filter_user_id').val(value);
							 	$('#filter-button').trigger('click');
							 	$('#dropdowns').removeClass("hidden");
							 }});
			$('#dropdowns').addClass("hidden");
			{% endif %}
		});
	</script>
	<script type='text/javascript' src='/media/js/jquery.linkselect.min.js'></script>
	<script type='text/javascript' src='/media/js/jquery.dataTables.min.js'></script>
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/profiles.css"/>
<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/jquery.linkselect.style.select.css"/>

<link rel="stylesheet" type="text/css" media="screen, projection" href="/media/css/jquery.dataTables_themeroller.css"/>
<div id="user-details">
	<div id="profile-img">
		{% if profile.gender %}
			<img src="media/img/profiles/blank_boy.png" alt="Default image">
		{% else %}
			<img src="media/img/profiles/blank_girl.png" alt="Default image">
		{% endif %}
		<br><a href="{% url auth_password_change %}">{% trans "Change password" %}</a>
		<br><a href="{% url profiles_edit_profile %}">{% trans "Edit Profile" %}</a>
	</div>
	<div id="profile-info"> 
		<p class="ui-state-default"> {{ profile.user.get_full_name }}</p>
		<p>Location: {{ profile.location }}</p>
		<p>Age:	{{ profile.get_age }}</p>
		{% if current_division %}
		<p>Grade:  {{current_division.division.age.age}},Division {{current_division.division.name}}</p>
		{% endif %}
		<p>Email: {{ profile.user.email }}</p>
		{% if is_moderator %}
		<p>
			Topics taught:
			{% for tt in topic_teacher%}
				{{tt.topic}} {{tt.division}} {% if not forloop.last %} , {% endif %}
			{% endfor %}
		</p>
		{% endif %}
	</div>
	{% if not is_moderator %}
	<div id="userStats">
		<div class="stats">
			<h2><img width="32" height="32" alt="" src="/media/img/profiles/icon-statsCheckin.png">{{stats_lessons_viewed}}</h2>
			<span class="translate">Lessons viewed</span>
		</div>
		<div class="stats">
			<h2><img width="32" height="32" alt="" src="/media/img/profiles/icon-statsDays.png">{{stats_exercises_completed}}</h2>
			<span class="translate">Exercises completed</span>
		</div>
		<div class="stats">
			<h2><img width="32" height="32" alt="" src="/media/img/profiles/icon-statsDones.png">{{stats_questions_submitted}}</h2>
			<span class="translate">Questions submitted</span>
		</div>
		<div class="stats statsLast"></div>
   </div>
   {% else %}
   <div id="student-div">
   		<p>Choose a student to view his/her report</p>
   		<select name="student-select" id="student-select">
			<option value = "0">Choose student</option>
			{% for s in students%}
			<option value = "{{s.student.user.id}}">{{s.student.user.get_full_name}}</option>	
			{% endfor %}
		</select>
   </div>
   {% endif %}
</div>



<div id="dropdowns">
	<form id="lesson-filter-form" method="get">
		<select name="age_group" class="linkselect">
			<option value = "0">All Grades</option>
			{% for a in all_age_groups %}
			<option value = "{{ a.age }}">{{a}}</option>	
			{% endfor %}
		</select>
		
		<select name="subject_id" class="linkselect">
			<option value = "0">All Subjects</option>
			{% for s in all_subjects %}
			<option value = "{{ s.id }}">{{s}}</option>	
			{% endfor %}
		</select>
		<input id="filter_user_id" name="user_id" type="hidden" value="0">
		<a id="filter-button" class="button-link">Filter</a>
	</form>
</div>

<div id="lessons-div">
	{% if not is_moderator %}
	{% include 'profiles/lesson_list.html' %}
	{% endif %}
</div>
{% endblock %}

templates/profiles/profile_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="post" action=".">{% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>
{% endblock %}